---
- name: Setup httpd webserver
  hosts: apache
  sudo: yes
  remote_user: root
  vars:
    homepage: 'Hello World from {{ inventory_hostname }}'
    old_port: 80
    new_port: 8080
    html_path: "/var/www/html/index.html"
  tasks:
    - name: install apache packages
      yum:
       name: httpd
       state: present
      tags:
       - deploy
    - name: ensure apache is at the latest version
      yum:
       name: httpd
       state: latest
      tags:
       - deploy
    - name: ensure httpd is running
      service:
       name: httpd
       state: started
      tags:
       - deploy
    - name: create index.html
      copy:
        dest: {{ html_path }}
        content: '{{ homepage }}'
      tags:
       - deploy
    - name: Open port 80 for http access
      firewalld:
       service: http
       permanent: true
       state: enabled
      notify:
       - restart firewall
      tags:
       - on_port80
    - name: restart firewall service
      service:
        name: firewalld
        state: restarted
      tags:
        - on_port80
    - name: update port
      lineinfile:
       path: '/etc/httpd/conf/httpd.conf'
       regexp: '^Listen {{ old_port }}'
       line: 'Listen {{ new_port }}'
      tags:
       - on_port8080
    - name: adding port to selinux
      shell: '/usr/sbin/semanage port -m -t http_port_t -p tcp {{ new_port }}'
      notify:
       - restart apache
      tags:
       - on_port8080
    - name: open port {{ new_port }} for http access
      firewalld:
       port: '{{ new_port }}/tcp'
       permanent: yes
       state: enabled
      notify:
      - restart firewall
      tags:
       - on_port8080
    - name: stop server
      yum:
       name: httpd
       state: removed
      tags:
        - undeploy
    - name: delete file example html
      file:
        path: {{ html_path }}
        state: absent
      tags:
        - undeploy
    - name: block port {{ new_port }} in firewall
      firewalld:
        port: '{{ new_port }}/tcp'
        permanent: yes
        state: disabled
      notify:
      - restart firewall
      tags:
      - undeploy
  handlers:
  - name: restart apache
    service:
     name: httpd
     state: restarted
  - name: restart firewall
    service:
     name: firewalld
     state: restarted
