---
- name: Setup httpd webserver
  hosts: apache
  sudo: yes
  remote_user: root
  vars:
    homepage: '<html><h1>Hello World print from {{ inventory_hostname }}</h1></html>'
  tasks:
    - name: install apache packages
      yum:
       name: httpd
       state: present
    - name: ensure apache is at the latest version
      yum:
      name: httpd
      state: latest
    - name: ensure httpd is running
      service:
       name: httpd
       state: started
    - name: open port 80 for http access
      firewalld:
       service: http
       permanent: true
       state: enabled
    - name: restart the firewalld service to load in the firewall changes
      service:
       name: firewalld
       state: restarted
    - name: Create index.html
      copy:
        dest: "/var/www/html/index.html"
        content: '{{ homepage }}'
 handlers:
    - name: restart apache
      service:
        name: httpd
        state: restarted
